# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dalmate Blog
email: ducla@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This site is used to collect some info that I've got when study. Please inbox me if you want to improve it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dalmatele.github.io" # the base hostname & protocol for your site
twitter_username: N/A
github_username:  dalmatele
comments: true
# Build settings
markdown: kramdown
#theme

theme: minimaå
